<?php
/**
 * CardInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Soxyl\Saferpay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Saferpay JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.10.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Soxyl\Saferpay;

/**
 * CardInfoTest Class Doc Comment
 *
 * @category    Class
 * @description CardInfo
 * @package     Soxyl\Saferpay
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CardInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CardInfo"
     */
    public function testCardInfo()
    {
    }

    /**
     * Test attribute "masked_number"
     */
    public function testPropertyMaskedNumber()
    {
    }

    /**
     * Test attribute "exp_year"
     */
    public function testPropertyExpYear()
    {
    }

    /**
     * Test attribute "exp_month"
     */
    public function testPropertyExpMonth()
    {
    }

    /**
     * Test attribute "holder_name"
     */
    public function testPropertyHolderName()
    {
    }

    /**
     * Test attribute "country_code"
     */
    public function testPropertyCountryCode()
    {
    }

    /**
     * Test attribute "hash_value"
     */
    public function testPropertyHashValue()
    {
    }
}
