<?php
/**
 * ErrorResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Soxyl\Saferpay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Saferpay JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.10.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Soxyl\Saferpay;

/**
 * ErrorResponseTest Class Doc Comment
 *
 * @category    Class
 * @description ErrorResponse
 * @package     Soxyl\Saferpay
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ErrorResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ErrorResponse"
     */
    public function testErrorResponse()
    {
    }

    /**
     * Test attribute "response_header"
     */
    public function testPropertyResponseHeader()
    {
    }

    /**
     * Test attribute "behavior"
     */
    public function testPropertyBehavior()
    {
    }

    /**
     * Test attribute "error_name"
     */
    public function testPropertyErrorName()
    {
    }

    /**
     * Test attribute "error_message"
     */
    public function testPropertyErrorMessage()
    {
    }

    /**
     * Test attribute "transaction_id"
     */
    public function testPropertyTransactionId()
    {
    }

    /**
     * Test attribute "error_detail"
     */
    public function testPropertyErrorDetail()
    {
    }

    /**
     * Test attribute "processor_name"
     */
    public function testPropertyProcessorName()
    {
    }

    /**
     * Test attribute "processor_result"
     */
    public function testPropertyProcessorResult()
    {
    }

    /**
     * Test attribute "processor_message"
     */
    public function testPropertyProcessorMessage()
    {
    }
}
