<?php
/**
 * ThreeDsInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Soxyl\Saferpay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Saferpay JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.10.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Soxyl\Saferpay;

/**
 * ThreeDsInfoTest Class Doc Comment
 *
 * @category    Class
 * @description ThreeDsInfo
 * @package     Soxyl\Saferpay
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ThreeDsInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ThreeDsInfo"
     */
    public function testThreeDsInfo()
    {
    }

    /**
     * Test attribute "authenticated"
     */
    public function testPropertyAuthenticated()
    {
    }

    /**
     * Test attribute "liability_shift"
     */
    public function testPropertyLiabilityShift()
    {
    }

    /**
     * Test attribute "xid"
     */
    public function testPropertyXid()
    {
    }

    /**
     * Test attribute "verification_value"
     */
    public function testPropertyVerificationValue()
    {
    }
}
