<?php
/**
 * TransactionInitializeRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Soxyl\Saferpay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Saferpay JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.10.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Soxyl\Saferpay;

/**
 * TransactionInitializeRequestTest Class Doc Comment
 *
 * @category    Class
 * @description TransactionInitializeRequest
 * @package     Soxyl\Saferpay
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TransactionInitializeRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TransactionInitializeRequest"
     */
    public function testTransactionInitializeRequest()
    {
    }

    /**
     * Test attribute "request_header"
     */
    public function testPropertyRequestHeader()
    {
    }

    /**
     * Test attribute "config_set"
     */
    public function testPropertyConfigSet()
    {
    }

    /**
     * Test attribute "terminal_id"
     */
    public function testPropertyTerminalId()
    {
    }

    /**
     * Test attribute "payment"
     */
    public function testPropertyPayment()
    {
    }

    /**
     * Test attribute "payment_means"
     */
    public function testPropertyPaymentMeans()
    {
    }

    /**
     * Test attribute "payer"
     */
    public function testPropertyPayer()
    {
    }

    /**
     * Test attribute "return_urls"
     */
    public function testPropertyReturnUrls()
    {
    }

    /**
     * Test attribute "styling"
     */
    public function testPropertyStyling()
    {
    }

    /**
     * Test attribute "wallet"
     */
    public function testPropertyWallet()
    {
    }

    /**
     * Test attribute "payment_methods"
     */
    public function testPropertyPaymentMethods()
    {
    }

    /**
     * Test attribute "card_form"
     */
    public function testPropertyCardForm()
    {
    }
}
