<?php
/**
 * TransactionApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Soxyl\Saferpay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Saferpay JSON API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.10.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Soxyl\Saferpay;

use \Soxyl\Saferpay\Configuration;
use \Soxyl\Saferpay\ApiException;
use \Soxyl\Saferpay\ObjectSerializer;

/**
 * TransactionApiTest Class Doc Comment
 *
 * @category Class
 * @package  Soxyl\Saferpay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TransactionApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for transactionAdjustAmountPost
     *
     * .
     *
     */
    public function testTransactionAdjustAmountPost()
    {
    }

    /**
     * Test case for transactionAssertCapturePost
     *
     * .
     *
     */
    public function testTransactionAssertCapturePost()
    {
    }

    /**
     * Test case for transactionAssertRedirectPaymentPost
     *
     * .
     *
     */
    public function testTransactionAssertRedirectPaymentPost()
    {
    }

    /**
     * Test case for transactionAssertRefundPost
     *
     * .
     *
     */
    public function testTransactionAssertRefundPost()
    {
    }

    /**
     * Test case for transactionAuthorizeDirectPost
     *
     * .
     *
     */
    public function testTransactionAuthorizeDirectPost()
    {
    }

    /**
     * Test case for transactionAuthorizePost
     *
     * .
     *
     */
    public function testTransactionAuthorizePost()
    {
    }

    /**
     * Test case for transactionAuthorizeReferencedPost
     *
     * .
     *
     */
    public function testTransactionAuthorizeReferencedPost()
    {
    }

    /**
     * Test case for transactionCancelPost
     *
     * .
     *
     */
    public function testTransactionCancelPost()
    {
    }

    /**
     * Test case for transactionCapturePost
     *
     * .
     *
     */
    public function testTransactionCapturePost()
    {
    }

    /**
     * Test case for transactionInitializePost
     *
     * .
     *
     */
    public function testTransactionInitializePost()
    {
    }

    /**
     * Test case for transactionMultipartCapturePost
     *
     * .
     *
     */
    public function testTransactionMultipartCapturePost()
    {
    }

    /**
     * Test case for transactionMultipartFinalizePost
     *
     * .
     *
     */
    public function testTransactionMultipartFinalizePost()
    {
    }

    /**
     * Test case for transactionQueryPaymentMeansPost
     *
     * .
     *
     */
    public function testTransactionQueryPaymentMeansPost()
    {
    }

    /**
     * Test case for transactionRedirectPaymentPost
     *
     * .
     *
     */
    public function testTransactionRedirectPaymentPost()
    {
    }

    /**
     * Test case for transactionRefundDirectPost
     *
     * .
     *
     */
    public function testTransactionRefundDirectPost()
    {
    }

    /**
     * Test case for transactionRefundPost
     *
     * .
     *
     */
    public function testTransactionRefundPost()
    {
    }
}
